Upload JUnit Reports

diff --git a/.github/workflows/gradle-build.yml b/.github/workflows/gradle-build.yml
--- a/.github/workflows/gradle-build.yml
+++ b/.github/workflows/gradle-build.yml
@@ -23,6 +23,12 @@ jobs:
       - name: Test with Gradle
         run: ./gradlew test
 
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+            report_paths: '**/build/test-results/test/TEST-*.xml'
+
       - name: Build with Gradle
         run: ./gradlew build
 
